[workspace]
resolver = "3"
members = [
    "rlox",
    "rlox_ast",
    "rlox_codegen",
    "rlox_parser",
    "rlox_scanner",
    "rlox_semantic"
]

[workspace.package]
edition = "2024"
rust-version = "1.86"
