[package]
name = "rlox"
version = "0.1.0"
license = "MIT"
description = "A LOX compiler written in Rust."
repository = "https://github.com/ID-UNCLEAR/rlox"
edition.workspace = true
rust-version.workspace = true
include = [
    "src/**/*.rs"
]
