name: 'CI: Build, Test and Format'

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test - ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cross
        run: |
          cargo binstall cross

      - name: Build
        run: |
          cross build --target ${{ matrix.target }} --release

      - name: Clippy
        run: |
          cross clippy --target ${{ matrix.target }} --release

      - name: Test
        if: endsWith(matrix.target, 'linux-gnu')
        run: |
          cross test --target ${{ matrix.target }} --release

      - name: Rename and move binary
        run: |
          mkdir -p dist
          EXT=""
          [[ "${{ matrix.target }}" == *windows* ]] && EXT=".exe"
          cp target/${{ matrix.target }}/release/rlox$EXT dist/rlox-${{ matrix.target }}$EXT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/*

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        run: |
          cargo fmt --all -- --check