name: 'CI: Build, Test and Format'

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test rlox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --release --verbose

      - name: Clippy
        run: |
          cargo clippy --release --verbose

      - name: Test
        run: |
          cargo test --release --verbose

  format:
    name: Format rlox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check formatting
        run: |
          cargo fmt --all -- --check